# Generated by Django 4.0.3 on 2022-03-25 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smpptransfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundmessage',
            name='received_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
