# Generated by Django 4.0.3 on 2022-03-25 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smpptransfer', '0004_inboundmessage_created_at_inboundmessage_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('source', models.CharField(max_length=15)),
                ('destination', models.CharField(max_length=15)),
                ('is_sent', models.BooleanField(default=False)),
                ('delivery_status', models.IntegerField(default=0)),
                ('received_at', models.DateTimeField(default=datetime.datetime.now)),
                ('sent_at', models.DateTimeField(blank=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
