# Generated by Django 4.0.3 on 2022-03-25 23:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smpptransfer', '0005_outboundmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('destination', models.TextField()),
                ('received_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_queued', models.BooleanField(default=False)),
            ],
        ),
    ]
