# Generated by Django 4.0.3 on 2022-03-25 23:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smpptransfer', '0006_sendcommand'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendcommand',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='sendcommand',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
