# Generated by Django 4.0.3 on 2022-07-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smpptransfer', '0008_sendcommand_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendcommand',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
