# Generated by Django 4.0.3 on 2022-07-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smpptransfer', '0009_sendcommand_is_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundmessage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='outboundmessage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sendcommand',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
