# Generated by Django 4.0.3 on 2022-07-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smpptransfer', '0010_alter_inboundmessage_id_alter_outboundmessage_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundmessage',
            name='msg_type',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('normal', 'Normal')], default='normal', max_length=20),
        ),
    ]
