# Generated by Django 4.0.3 on 2022-07-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smpptransfer', '0011_inboundmessage_msg_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundmessage',
            name='retrieved_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='delivered_at',
            field=models.DateTimeField(null=True),
        ),
    ]
