# Generated by Django 4.0.3 on 2022-07-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smpptransfer', '0012_inboundmessage_retrieved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundmessage',
            name='network',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
