# Generated by Django 4.0.3 on 2022-07-09 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smpptransfer', '0013_outboundmessage_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundmessage',
            name='attempts',
            field=models.IntegerField(default=1),
        ),
    ]
